import db from '../config/database.js';
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
export const getRequest=(id)=>db.prepare('SELECT * FROM service_requests WHERE id=?').get(id);
export const assertOwner=(request,user)=>{if(!request||request.client_id!==user.id)throw fail('Solicitação não encontrada.',404);};
export const requestDetails=(id)=>{const request=getRequest(id);if(!request)return null;request.services=db.prepare('SELECT service_name FROM request_services WHERE request_id=?').all(id).map(x=>x.service_name);return request;};
export const createRequest=(clientId,body)=>{const {address,propertySize,notes,scheduledAt,services,estimatedValue}=body;if(!address||!propertySize||!scheduledAt||!Array.isArray(services)||!services.length)throw fail('Endereço, tamanho, data e ao menos um serviço são obrigatórios.');if(Number.isNaN(Date.parse(scheduledAt))||new Date(scheduledAt)<=new Date())throw fail('O agendamento deve ser em data e horário futuros.');const create=db.transaction(()=>{const id=db.prepare('INSERT INTO service_requests(client_id,address,property_size,notes,scheduled_at,estimated_value) VALUES(?,?,?,?,?,?)').run(clientId,address.trim(),propertySize.trim(),notes?.trim()||null,new Date(scheduledAt).toISOString(),estimatedValue??null).lastInsertRowid;const add=db.prepare('INSERT INTO request_services(request_id,service_name) VALUES(?,?)');[...new Set(services.map(x=>String(x).trim()).filter(Boolean))].forEach(x=>add.run(id,x));return id;});return requestDetails(create());};
export const applyToRequest=(requestId,diaristId,body)=>{const request=getRequest(requestId);if(!request||request.status!=='ABERTA')throw fail('A solicitação não está disponível para candidatura.',409);const profile=db.prepare('SELECT verified,active FROM diarist_profiles WHERE user_id=?').get(diaristId);if(!profile?.verified||!profile.active)throw fail('Apenas diaristas verificadas e ativas podem candidatar-se.',403);const value=Number(body.proposedValue);if(!(value>0))throw fail('Informe um valor de proposta válido.');const conflict=db.prepare("SELECT 1 FROM applications a JOIN service_requests r ON r.id=a.request_id WHERE a.diarist_id=? AND a.status='ACEITA' AND r.scheduled_at=?").get(diaristId,request.scheduled_at);if(conflict)throw fail('Já existe um serviço aceito para este horário.',409);db.prepare('INSERT INTO applications(request_id,diarist_id,proposed_value,message) VALUES(?,?,?,?)').run(requestId,diaristId,value,body.message?.trim()||null);};
export const acceptApplication=(requestId,applicationId,client)=>db.transaction(()=>{const request=getRequest(requestId);assertOwner(request,client);if(!['ABERTA','EM_NEGOCIACAO'].includes(request.status))throw fail('Esta solicitação não pode mais receber uma confirmação.',409);const app=db.prepare("SELECT * FROM applications WHERE id=? AND request_id=? AND status='PENDENTE'").get(applicationId,requestId);if(!app)throw fail('Candidatura pendente não encontrada.',404);db.prepare("UPDATE applications SET status=CASE WHEN id=? THEN 'ACEITA' ELSE 'RECUSADA' END WHERE request_id=?").run(applicationId,requestId);db.prepare("UPDATE service_requests SET status='AGENDADA',estimated_value=? WHERE id=?").run(app.proposed_value,requestId);return requestDetails(requestId);})();
export const addReview=(requestId,client,body)=>{const request=getRequest(requestId);assertOwner(request,client);if(request.status!=='CONCLUIDA')throw fail('A avaliação só é permitida após a conclusão do serviço.',409);const app=db.prepare("SELECT diarist_id FROM applications WHERE request_id=? AND status='ACEITA'").get(requestId);if(!app)throw fail('Não há diarista confirmada para este serviço.',409);const rating=Number(body.rating);if(!Number.isInteger(rating)||rating<1||rating>5)throw fail('A nota deve ser um número inteiro entre 1 e 5.');db.prepare('INSERT INTO reviews(request_id,client_id,diarist_id,rating,comment,tags) VALUES(?,?,?,?,?,?)').run(requestId,client.id,app.diarist_id,rating,body.comment?.trim()||null,JSON.stringify(body.tags||[]));};
